"""animal_id in pose

Revision ID: 089fda6a1d6e
Revises: 3a72b4e55858
Create Date: 2022-11-07 12:58:55.967802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089fda6a1d6e'
down_revision = '3a72b4e55858'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pose_estimations', sa.Column('animal_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pose_estimations', 'animal_id')
    # ### end Alembic commands ###
