"""trial_id in strikes

Revision ID: 09f89c5d0d09
Revises: 2afea69b2340
Create Date: 2022-10-07 17:25:46.445838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09f89c5d0d09'
down_revision = '2afea69b2340'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strikes', sa.Column('trial_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'strikes', 'trials', ['trial_id'], ['id'])
    op.drop_column('trials', 'video_frames')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trials', sa.Column('video_frames', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'strikes', type_='foreignkey')
    op.drop_column('strikes', 'trial_id')
    # ### end Alembic commands ###
