"""max accl

Revision ID: 1e408b07bdd6
Revises: 4e167ef18097
Create Date: 2023-01-23 10:34:23.712094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e408b07bdd6'
down_revision = '4e167ef18097'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strikes', sa.Column('max_acceleration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strikes', 'max_acceleration')
    # ### end Alembic commands ###
