"""animal_settings

Revision ID: 2393a61c5cab
Revises: 1e408b07bdd6
Create Date: 2023-03-14 14:39:16.129011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2393a61c5cab'
down_revision = '1e408b07bdd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('animal_id', sa.String(), nullable=True),
    sa.Column('bug_types', sa.String(), nullable=True),
    sa.Column('reward_bugs', sa.String(), nullable=True),
    sa.Column('background_color', sa.String(), nullable=True),
    sa.Column('reward_any_touch_prob', sa.Float(), nullable=True),
    sa.Column('exit_hole', sa.String(), nullable=True),
    sa.Column('animal_id_key', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id_key'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('animals', sa.Column('reward_any_touch_prob', sa.Float(), nullable=True))
    op.add_column('animals', sa.Column('exit_hole', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'exit_hole')
    op.drop_column('animals', 'reward_any_touch_prob')
    op.drop_table('animal_settings')
    # ### end Alembic commands ###
