"""videos

Revision ID: 2afea69b2340
Revises: 9e953d48a222
Create Date: 2022-09-28 17:52:20.256186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2afea69b2340'
down_revision = '9e953d48a222'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_predictions', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_predictions', 'start_time')
    # ### end Alembic commands ###
