"""video is_compressed

Revision ID: 2b78c3fd0cf5
Revises: a0ef51ba34ec
Create Date: 2022-11-22 12:07:57.860733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b78c3fd0cf5'
down_revision = 'a0ef51ba34ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('is_compressed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'is_compressed')
    # ### end Alembic commands ###
