"""bug_types

Revision ID: 3a72b4e55858
Revises: d5adbe562083
Create Date: 2022-11-05 02:12:39.184402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a72b4e55858'
down_revision = 'd5adbe562083'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('bug_types', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'bug_types')
    # ### end Alembic commands ###
