"""animal_settings add sex

Revision ID: 3e869a7cb9e3
Revises: 2393a61c5cab
Create Date: 2023-03-14 14:44:56.223642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e869a7cb9e3'
down_revision = '2393a61c5cab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_settings', sa.Column('sex', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal_settings', 'sex')
    # ### end Alembic commands ###
