"""frame info in strikes

Revision ID: 4e167ef18097
Revises: 9613f590741b
Create Date: 2023-01-12 13:17:01.429993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e167ef18097'
down_revision = '9613f590741b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strikes', sa.Column('strike_frame', sa.Integer(), nullable=True))
    op.add_column('strikes', sa.Column('leap_frame', sa.Integer(), nullable=True))
    op.add_column('strikes', sa.Column('video_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'strikes', 'videos', ['video_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strikes', type_='foreignkey')
    op.drop_column('strikes', 'video_id')
    op.drop_column('strikes', 'leap_frame')
    op.drop_column('strikes', 'strike_frame')
    # ### end Alembic commands ###
