"""remove block_id from temperature

Revision ID: 5058517b3a98
Revises: a9a86aa14814
Create Date: 2022-09-22 15:58:12.855606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5058517b3a98'
down_revision = 'a9a86aa14814'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('temperatures_block_id_fkey', 'temperatures', type_='foreignkey')
    op.drop_column('temperatures', 'block_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperatures', sa.Column('block_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('temperatures_block_id_fkey', 'temperatures', 'blocks', ['block_id'], ['id'])
    # ### end Alembic commands ###
