"""pose_estimations

Revision ID: 55abc1d64e9c
Revises: 314cdf38ac34
Create Date: 2022-10-30 11:59:17.321028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55abc1d64e9c'
down_revision = '314cdf38ac34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pose_estimations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cam_name', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('angle', sa.Float(), nullable=True),
    sa.Column('engagement', sa.Float(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pose_estimations')
    # ### end Alembic commands ###
