"""animal_id as string2

Revision ID: 650f2591a8b3
Revises: 815ef97ff508
Create Date: 2022-11-07 16:18:42.965753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650f2591a8b3'
down_revision = '815ef97ff508'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
