"""add sensor to temperature

Revision ID: 712c3537a5f6
Revises: d1e35203f184
Create Date: 2023-03-28 11:28:42.844346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712c3537a5f6'
down_revision = 'd1e35203f184'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperatures', sa.Column('sensor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temperatures', 'sensor')
    # ### end Alembic commands ###
