"""animal_id as string

Revision ID: 815ef97ff508
Revises: 089fda6a1d6e
Create Date: 2022-11-07 15:58:14.181771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815ef97ff508'
down_revision = '089fda6a1d6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
