"""add arena name to schedule

Revision ID: 9f5f24bed804
Revises: 712c3537a5f6
Create Date: 2023-03-29 11:26:40.080723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5f24bed804'
down_revision = '712c3537a5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('arena', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'arena')
    # ### end Alembic commands ###
