"""model in pose

Revision ID: a03be2bafd15
Revises: ee0ff6ff4e4e
Create Date: 2022-12-25 14:42:22.946174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03be2bafd15'
down_revision = 'ee0ff6ff4e4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pose_estimations', sa.Column('model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pose_estimations', 'model')
    # ### end Alembic commands ###
