"""revert block_id from temperature

Revision ID: a8cd4f81afc1
Revises: 5058517b3a98
Create Date: 2022-09-22 16:08:41.999664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8cd4f81afc1'
down_revision = '5058517b3a98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperatures', sa.Column('block_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'temperatures', 'blocks', ['block_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temperatures', type_='foreignkey')
    op.drop_column('temperatures', 'block_id')
    # ### end Alembic commands ###
