"""remove srikes from trials

Revision ID: a9a86aa14814
Revises: 6a8afdc0a5f8
Create Date: 2022-09-17 16:05:27.929869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a86aa14814'
down_revision = '6a8afdc0a5f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
