"""video compression_status

Revision ID: b16990172ba5
Revises: 2b78c3fd0cf5
Create Date: 2022-11-22 12:36:11.293746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16990172ba5'
down_revision = '2b78c3fd0cf5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('compression_status', sa.Integer(), nullable=True))
    op.drop_column('videos', 'is_compressed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('is_compressed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('videos', 'compression_status')
    # ### end Alembic commands ###
