"""extend strike params

Revision ID: c54164f8cdca
Revises: cf9fff890dee
Create Date: 2022-11-09 15:10:24.990622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c54164f8cdca'
down_revision = 'cf9fff890dee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strikes', sa.Column('prediction_distance', sa.Float(), nullable=True))
    op.add_column('strikes', sa.Column('calc_speed', sa.Float(), nullable=True))
    op.add_column('strikes', sa.Column('projected_strike_coords', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('strikes', sa.Column('projected_leap_coords', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strikes', 'projected_leap_coords')
    op.drop_column('strikes', 'projected_strike_coords')
    op.drop_column('strikes', 'calc_speed')
    op.drop_column('strikes', 'prediction_distance')
    # ### end Alembic commands ###
