"""add arena name to reward

Revision ID: f3dd993d5af6
Revises: 9f5f24bed804
Create Date: 2023-03-29 11:27:16.833907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3dd993d5af6'
down_revision = '9f5f24bed804'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('arena', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'arena')
    # ### end Alembic commands ###
