"""add arena name to animal settings

Revision ID: fdef62f70679
Revises: a42143d99221
Create Date: 2023-03-29 14:08:38.378353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdef62f70679'
down_revision = 'a42143d99221'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_settings', sa.Column('arena', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal_settings', 'arena')
    # ### end Alembic commands ###
