FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

USER root

ENV TZ=Asia/Jerusalem
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN mkdir /data

COPY ./requirements .
RUN pip install -r pose.txt

RUN pip uninstall -y tensorflow
RUN pip install tensorflow-gpu==1.13.1
