FROM python:3.7

RUN mkdir /explore
WORKDIR /explore

COPY ./requirements .

RUN pip install -r arena.txt

ENV TZ=Asia/Jerusalem
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone