FROM nablascom/cuda-pytorch

RUN mkdir /logger
WORKDIR /logger

COPY ./requirements .

RUN pip install -r pose.txt

ENV TZ=Asia/Jerusalem
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone