FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

ARG DEBIAN_FRONTEND
ENV DEBIAN_FRONTEND=noninteractive
# Install dependencies
RUN apt-get -qq update && apt-get -qq upgrade -y && apt-get -qq install -y \
  wget \
  unzip \
  libtbb2 \
  libtbb-dev && \
apt-get -qq install -y \
  build-essential \
  cmake \
  git \
  x11-xserver-utils \
  pkg-config \
  libjpeg8-dev \
  libtiff5-dev \
  libpng-dev \
  libgtk2.0-dev \
  libgtk3.0 \
  libnotify-dev \
  libavcodec-dev \
  libavformat-dev \
  libswscale-dev \
  libv4l-dev \
  libatlas-base-dev \
  gfortran \
  libhdf5-dev \
  python3.7-dev \
  python3-tk \
  ffmpeg \
  libsm6 \
  libxext6 \
  libjsoncpp-dev


RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
RUN apt-get -qq install -y python3-pip && \
pip3 install --upgrade pip && \
apt-get autoclean && apt-get clean && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh
RUN ln -s ~/miniconda3/bin/conda /usr/local/bin/conda
RUN ln -s ~/miniconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh

RUN conda create -n anipose python=3.7 tensorflow-gpu=1.13.1
RUN conda run -n anipose bash -c "pip install deeplabcut"
RUN conda run -n anipose bash -c "pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython"
RUN conda run -n anipose bash -c "pip install anipose"
RUN conda run -n anipose bash -c "conda install -y mayavi ffmpeg"
RUN conda run -n anipose bash -c "pip install --upgrade apptools"
RUN conda run -n anipose bash -c "conda install -c conda-forge -y jsoncpp"

RUN echo ". /root/miniconda3/etc/profile.d/conda.sh" >> /root/.bashrc
RUN echo "source activate anipose" >> /root/.bashrc