FROM python:3.6

RUN mkdir /logger
WORKDIR /logger

COPY ./requirements .

RUN pip install -r arena.txt

ENV TZ=Asia/Jerusalem
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone